export const state = {
  leadsData: null,
  oppData: null,
  activeResults: [],
  inactiveResults: [],
  unassignedResults: [],
  masterMap: new Map(),
  changeLog: [],
  realtorOwnerMap: new Map(),
  currentMode: 'active',
  sortCol: 'cnt',
  sortDir: -1,
  dbConnected: false,
  loReferenceMap: new Map(),
  loActiveResults: [],
  loInactiveResults: [],
  loUnassignedResults: [],
  loMasterMap: new Map(),
  loCurrentMode: 'active',
  loSortCol: 'cnt',
  loSortDir: -1,
  loPendingRender: new Set(),
  loCurrentTab: 'med',
  loAllowedOwners: [],
  callsData: [],
  zoomData: [],
  doNotCountMeetings: new Set(),
  zoomParticipantLabels: new Map(),
  // Visibilidad por BD (solo DISPLAY; el cálculo usa todos los datos)
  visibilityLoaded: false,
  fullAccess: false,
  visibleBdSet: new Set(),
  visibleBdNames: [],
  // Selector de estrategia (solo DISPLAY, como visibilidad): 'all' | 'b2b' | 'nppm'.
  // Por defecto 'all' para no cambiar los totales que la gente ve al abrir.
  strategyFilter: 'all'
};
